### ISSUE TITLE
Remotes fr cloudyr/RoogleVision not working

### ISSUE THREAD

**Issue by mrecos** [mrecos/signboardr#1]
importing cloudyr/RoogleVision package using "Remotes:" in DESCRIPTION not working on RSTUDIO server (WholeTale). Pasted functions into funcs.R to test passing CI. Need to figure out Remotes

**Comment by mrecos** [comment]
simply needed RoogleVision package name under Imports: as well as Remotes: in DESCRIPTION

**Comment by benmarwick** [comment]
Huh, that is good to know!
